### ISSUE TITLE
Не се зареждат online презентациите

### ISSUE THREAD

**Issue by TsvetiG** [TelerikAcademy/Mobile-Applications-for-Android#2]
При опит да се отворят презентациите от "02. Introduction-to-Java" натам получавам грешка "404 Not Found"

**Comment by kossov** [comment]
presentation > slides > index.html copy link > rawgit.com paste link > copy Use this URL for dev/testing link > paste in browser

**Comment by NikolayIT** [comment]
@kossov Create a pull request :smile:

**Comment by TsvetiG** [comment]
Thanks :)
